<?php

/**
 * @file
 *  Implements some customizations for the order content type.
 */

/**
 * @todo: We will have to write our own NodeSelection validator, that extends
 * the Drupal\node\Plugin\EntityReferenceSelection\NodeSelection so that we can
 * reference unpublished entities when the users create orders. Until them, we
 * have to keep the order_item nodes published.
 */

/**
 * Implements hook_menu_local_tasks_alter().
 */
function emarket_order_menu_local_tasks_alter(&$data, $route_name) {
  // If we are on a node route, keep the order_hash query parameter for all the
  // tabs.
  if (strpos($route_name, 'entity.node.') === 0) {
    $order_hash = \Drupal::request()->get('order_hash');
    if (!empty($order_hash)) {
      foreach ($data['tabs'] as $index => $routes) {
        foreach ($routes as $route_key => $route_info) {
          if (strpos($route_key, 'entity.node.') === 0) {
            $query = $route_info['#link']['url']->getOption('query');
            $query['order_hash'] = $order_hash;
            $route_info['#link']['url']->setOption('query', $query);
          }
        }
      }
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function emarket_order_module_implements_alter(&$implementations, $hook) {
  // We need our form alter hooks to run at the end.
  if ($hook == 'form_alter') {
    $group = $implementations['emarket_order'];
    unset($implementations['emarket_order']);
    $implementations['emarket_order'] = $group;
  }
}

/**
 * Implements hook_form_alter().
 *
 * Dummy form alter hook, otherwise the module_implements_alter() will not work.
 * We will just keep this emtpy hook until a better solution will be found.
 */
function emarket_order_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function emarket_order_form_node_order_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // When the current user is anonymous, we want to have the email field
  // required. For the case when the user is logged in, we actually want to have
  // the field hidden.
  // @todo: alter also the node edit form!
  if (\Drupal::currentUser()->isAnonymous()) {
    $form['field_email']['widget'][0]['value']['#required'] = TRUE;
  } else {
    $form['field_email']['#access'] = FALSE;
  }
  $form['actions']['submit']['#submit'][] = 'emarket_order_node_order_form_submit_redirect';
  emarket_order_order_form_alter($form, $form_state, $form_id);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function emarket_order_form_node_order_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  emarket_order_form_node_order_form_alter($form, $form_state, $form_id);
}

/**
 * Performs common alterations for the node order form (add and edit).
 */
function emarket_order_order_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Also, the title should not be mandatory.
  //$form['title']['widget']['0']['value']['#required'] = FALSE;
  $form['actions']['submit']['#submit'][] = 'emarket_order_form_submit_preserve_hash';
}

/**
 * Submit handler that will set the order hash in the current request upon a
 * form submission.
 */
function emarket_order_node_order_form_submit_redirect(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $node = \Drupal\node\Entity\Node::load($form_state->get('nid'));
  if (!empty($node)) {
    emarket_order_set_order_hash_in_request($node);
    $form_state->setRedirect("entity.node.canonical", array('node' => $node->id()));
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the comment form.
 */
function emarket_order_form_comment_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // For comments on orders or order_items we want to always go to the order
  // view after submission, with an anchor to the comment, not to the comment
  // full view.
  /* @var \Drupal\comment\Entity\Comment $comment_entity */
  $comment_entity = $form_state->getBuildInfo()['callback_object']->getEntity();
  if ($comment_entity->getCommentedEntityTypeId() == 'node' &&
    ($comment_entity->getCommentedEntity()->bundle() == 'order' || $comment_entity->getCommentedEntity()->bundle() == 'order_item')) {
    $form['actions']['submit']['#submit'][] = 'emarket_order_comment_form_submit_redirect';
    $form['actions']['submit']['#submit'][] = 'emarket_order_form_submit_preserve_hash';
    $form['author']['name']['#access'] = FALSE;
    $form['subject']['#access'] = FALSE;
  }
}

/**
 * Additional submit handler for the comment forms on order and order items to
 * redirect the user to the order view page.
 */
function emarket_order_comment_form_submit_redirect(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  /* @var \Drupal\comment\Entity\Comment $comment_entity */
  $comment_entity = $form_state->getBuildInfo()['callback_object']->getEntity();
  $commented_entity = $comment_entity->getCommentedEntity();
  $redirect_options = array(
    'fragment' => 'comment-' . $comment_entity->id(),
  );
  $order_entity = NULL;
  if ($commented_entity->bundle() == 'order') {
    $order_entity = $commented_entity;
  }
  // Although the only possibility here is to have order or order_item as
  // bundle, we do the check again to make that clear when reading the code and
  // also robust for future changes.
  elseif ($commented_entity->bundle() == 'order_item') {
    try {
      $order_entity = emarket_order_get_order_from_order_item($commented_entity);
    }
    catch (\InvalidArgumentException $e) {
      // Do nothing special here, maybe just log it? @todo
    }
  }
  if (!empty($order_entity)) {
    // We also want to append the hash to the redirect in case the user is not
    // logged in.
    if (\Drupal::currentUser()->isAnonymous()) {
      $redirect_options['query']['order_hash'] = emarket_order_get_hash_for_order($order_entity);
    }
    $form_state->setRedirect("entity.node.canonical", array('node' => $order_entity->id()), $redirect_options);
  }
}

/**
 * Implements hook_inline_entity_form_table_fields_alter().
 */
function emarket_order_inline_entity_form_table_fields_alter(&$fields, $context) {
  // For the order items field, we want to add some additional fields to be
  // displayed in the overview table, as well as remove the status field which
  // is useless.
  if ($context['entity_type'] == 'node' && $context['field_name'] == 'field_order_items') {
    unset($fields['status']);
    $fields['field_quantity'] = array(
      'type' => 'field',
      'label' => t('Quantity'),
      'weight' => $fields['label']['weight'] + 1,
    );
    $fields['field_store'] = array(
      'type' => 'field',
      'label' => t('Store'),
      'weight' => $fields['label']['weight'] + 2,
    );
    $fields['field_description'] = array(
      'type' => 'field',
      'label' => t('Description'),
      'weight' => $fields['label']['weight'] + 3,
    );
  }
}

/**
 * Additional submit handler for the order node form.
 */
function emarket_order_form_submit_preserve_hash(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  // Preserve the order_hash if we have it in the query.
  $order_hash = \Drupal::request()->get('order_hash');
  if (!empty($order_hash)) {
    $redirect = $form_state->getRedirect();
    if (!empty($redirect) && $redirect instanceof \Drupal\Core\Url) {
      $query = $redirect->getOption('query');
      $query['order_hash'] = $order_hash;
      $redirect->setOption('query', $query);
    }
  }
}

/**
 * Implements hook_mail().
 */
function emarket_order_mail($key, &$message, $params) {
  /*$token_service = \Drupal::token();
  $language_manager = \Drupal::languageManager();
  $langcode = $message['langcode'];
  $variables = array('user' => $params['account']);

  $language = \Drupal::languageManager()->getLanguage($params['account']->getPreferredLangcode());
  $original_language = $language_manager->getConfigOverrideLanguage();
  $language_manager->setConfigOverrideLanguage($language);
  $mail_config = \Drupal::config('user.mail');

  $token_options = ['langcode' => $langcode, 'callback' => 'user_mail_tokens', 'clear' => TRUE];*/
  switch ($key) {
    case '_draft': {
      $url = \Drupal\Core\Url::fromUserInput('/node/' . $params['entity']->id(), array('query' => array('order_hash' => emarket_order_get_hash_for_order($params['entity'])), 'absolute' => TRUE));
      $message['subject'] = t('Order set to draft', array(), array('langcode' => $message['langcode']));
      $message['body'][] = t('You have set an order to draft. To view the order, follow this url: !url', array('!url' => $url->toString()), array('langcode' => $message['langcode']));
      //$message['body'][] = t('You have set an order to draft. To view the order, follow this url: !url', array(), array('langcode' => $message['langcode']));
      break;
    }
    case 'draft_submitted': {
      $message['subject'] = t('Order set to submitted', array(), array('langcode' => $message['langcode']));
      $message['body'][] = t('You have set an order to submitted: ' . $params['entity']->id(), array(), array('langcode' => $message['langcode']));
      break;
    }
  }
  //$language_manager->setConfigOverrideLanguage($original_language);
}

/**
 * Implements hook_entity_field_access().
 */
function emarket_order_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  switch ($field_definition->getName()) {
    // We deny the access to the field_order (which is attached to the
    // order_item content type) to the users who do not have administer
    // permissions.
    case 'field_order': {
      // Only the admins can view the field at the moment, but not event they
      // can edit it.
      if ($operation == 'view' && $account->hasPermission('administer nodes')) {
        return \Drupal\Core\Access\AccessResult::allowed();
      }
      return \Drupal\Core\Access\AccessResult::forbidden();
      break;
    }
    case 'comment':
    case 'revision_log': {
      // Also, deny the access to the comment field setting on the node edit
      // form, as well as to the revision log field. For the comments field, we
      // do not want to remove it from the content type form display
      // configuration, admins should still see that field.
      if ($operation == 'edit' && !$account->hasPermission('adminster nodes')) {
        return \Drupal\Core\Access\AccessResult::forbidden();
      }
      break;
    }
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function emarket_order_node_presave(\Drupal\node\NodeInterface $node) {
  // For new orders, if the user is authenticated, then we directly set them as
  // confirmed.
  if ($node->isNew() && $node->bundle() == 'order') {
    $author = $node->getRevisionAuthor();
    if ($author->isAuthenticated()) {
      $node->set('field_order_confirmed', 1);
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function emarket_order_node_insert(\Drupal\node\NodeInterface $node) {
  // For now, we just need the same things as the update hook does.
  emarket_order_node_update($node);
}

/**
 * Implements hook_ENTITY_TYPE_update() for nodes.
 *
 * @param \Drupal\node\NodeInterface $node
 */
function emarket_order_node_update(\Drupal\node\NodeInterface $node) {
  // When we update an order, we will check all the order items, and for the
  // ones which do not have the order reference set, we will update them.
  // @todo: find a more performant way of doing this.
  if ($node->bundle() == 'order') {
    try {
      $order_items = $node->get('field_order_items')->referencedEntities();
      if (!empty($order_items)) {
        foreach ($order_items as $order_item) {
          $order_reference = $order_item->get('field_order')->getValue();
          if (empty($order_reference)) {
            $order_item->get('field_order')->setValue(array('target_id' => $node->id()));
            $order_item->save();
          }
        }
      }
    }
    catch (\InvalidArgumentException $e) {
      // Do nothing special here, maybe just log it? @todo
    }
  }
}

/**
 * Implements hook_node_access().
 */
function emarket_order_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  // For orders, any user which has the special link with the hash in it has
  // access to view, edit or delete. The same for the order item nodes.
  // @todo: the service providers to which this node is assigned also have
  // access to view it.
  // @todo: we should maybe remove the order item nodes and just use a custom
  // field. But it is true that the system is much more flexible with nodes.
  // Some for deleting. When we implement this, then we can update the
  // permissions.
  if ($op == 'update' || $op == 'view' || $op == 'delete') {
    $node_to_check = NULL;
    switch ($node->bundle()) {
      // For order item nodes, we actually have to check the access to their
      // parent order.
      case 'order_item': {
        try {
          $node_to_check = emarket_order_get_order_from_order_item($node);
        }
        catch (\InvalidArgumentException $e) {
          // Do nothing special here, maybe just log it? @todo
        }
        break;
      }
      case 'order': {
        $node_to_check = $node;
        break;
      }
    }

    if (!empty($node_to_check)) {
      $hash = \Drupal::request()->get('order_hash');
      $valid_hash = emarket_order_get_hash_for_order($node_to_check);
      if ($hash === $valid_hash) {
        return \Drupal\Core\Access\AccessResult::allowed();
      }
      // If we are here, we can still allow the user to view the node in case
      // he is the service provider.
      if ($op == 'view' && $account->isAuthenticated()) {
        try {
          $service_provider = $node_to_check->get('field_service_provider')->referencedEntities();
          if (!empty($service_provider) && $service_provider[0]->id() == $account->id()) {
            return \Drupal\Core\Access\AccessResult::allowed();
          }
        }
        catch (\InvalidArgumentException $e) {
          // Do nothing special here, maybe just log it? @todo
        }
      }
    }
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}

/**
 * Helper function to compute the hash for an order.
 *
 * @param \Drupal\node\NodeInterface $node
 *  The order node.
 */
function emarket_order_get_hash_for_order(\Drupal\node\NodeInterface $node) {
  $data = $node->id() . '-' . $node->getCreatedTime();
  return \Drupal\Component\Utility\Crypt::hashBase64($data, \Drupal\Core\Site\Settings::getHashSalt());
}

/**
 * Helper function to set the hash of an order in the current request.
 *
 * @param \Drupal\node\NodeInterface $node
 *  The order node.
 * @param boolean $force_set
 *  If we should force set the order hash, even if we already have a value.
 */
function emarket_order_set_order_hash_in_request(\Drupal\node\NodeInterface $node, $force_set = FALSE) {
  // First, make sure we do not already have one. If we do have one, just skip
  // setting it again.
  $order_hash = \Drupal::request()->get('order_hash');
  if (empty($order_hash) || $force_set) {
    \Drupal::request()->query->set('order_hash', emarket_order_get_hash_for_order($node));
  }
}

/**
 * Helper function to return the order from an order item.
 *
 * @param \Drupal\node\NodeInterface $order_item
 *  The order item node.
 * @throws \InvalidArgumentException
 *  Because it calls the Drupal\Core\Entity\FieldableEntityInterface::get()
 *  which can throw the \InvalidArgumentException when the name of the field
 *  does not exit. We do not want to catch the exception here because we do not
 *  want what to do with it, if we should break the execution, log it with a
 *  specific message, etc... The code which calls
 *  emarket_order_get_order_from_order_item() is responsible for catching it.
 * @return \Drupal\node\NodeInterface|NULL
 *  The order object, if the order item has an order. Otherwise, NULL.
 */
function emarket_order_get_order_from_order_item(\Drupal\node\NodeInterface $order_item) {
  $order_field = $order_item->get('field_order')->referencedEntities();
  if (!empty($order_field)) {
    return $order_field[0];
  }
  return NULL;
}

/**
 * Implements hook_workbench_moderation_valid_transitions_alter().
 */
function emarket_order_workbench_moderation_valid_transitions_alter(array &$transitions, \Drupal\Core\Entity\ContentEntityInterface $entity, \Drupal\Core\Session\AccountInterface $user) {
  // We do our alteration only for order items. We will have to check if the
  // account is the owner or the service provider of the entity. Based on this,
  // we will have to unset different transitions.
  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'order' && !$user->hasPermission('administer nodes')) {
    $user_role = emarket_order_get_role_for_order($entity, $user);
    $valid_transitions = emarket_order_get_valid_transitions_per_user_role($user_role, $entity);
    if (empty($valid_transitions)) {
      $valid_transitions = array();
    }

    $transitions = array_intersect_key($transitions, array_flip($valid_transitions));
  }
}

/**
 * Shutdown callback for notifying about a transition.
 *
 * @param $uuid
 *  The uuid of the entity.
 * @param $transition_key
 *  The transition key. @see StateTransitionSubscriber::getInterestedStateTransitions()
 */
function emarket_order_notification_shutdown_callback($uuid, $transition_key) {
  $nodes = Drupal::entityTypeManager()->getStorage('node')->loadByProperties(array('uuid' => $uuid));
  if (!empty($nodes)) {
    $node = reset($nodes);
    emarket_order_notify($node, $transition_key);
  }
}

function emarket_order_notify($node, $transition_key) {
  $recipients = emarket_order_notification_recipients($node, $transition_key);
  foreach ($recipients as $recipient) {
    // Currently, we notify only by mail.
    if ($recipient['type'] == 'mail') {
      $params = array('entity' => $node);
      \Drupal::service('plugin.manager.mail')->mail('emarket_order', $transition_key, $recipient['value'], \Drupal::languageManager()->getDefaultLanguage()->getId(), $params);
    }
  }
}

/**
 * Returns an array with all the notification recipients when a transition
 * happens for an order.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *  The entity for which the transition is happening.
 * @param $transition_key
 *  The key of the transition, @see StateTransitionSubscriber::getInterestedStateTransitions()
 */
function emarket_order_notification_recipients(\Drupal\node\NodeInterface $node, $transition_key) {
  $recipients = array();
  $author = $node->getOwner();
  // If the author is anonymous, we will take the e-mail of the node.
  if ($author->isAnonymous()) {
    $author_mail = $node->get('field_email')->getValue();
    $author_mail = $author_mail[0]['value'];
  }
  else {
    $author_mail = $author->getEmail();
  }
  switch ($transition_key) {
    // The case for when the order is created.
    case 'draft_submitted':
    case '_draft': {
      $recipients[] = array(
        'type' => 'mail',
        'value' => $author_mail,
      );
    }
  }
  return $recipients;
}

/**
 * Returns the role of an user in the context of an order.
 *
 * @param \Drupal\user\EntityOwnerInterface $order
 *  The node order object.
 * @param \Drupal\Core\Session\AccountInterface $user
 *  The user account object.
 * @return string|FALSE
 *  The role name, which can be 'author' or 'service_provider', or 'none' if
 *  the role could not be identified.
 */
function emarket_order_get_role_for_order(\Drupal\Core\Entity\ContentEntityInterface $order, \Drupal\Core\Session\AccountInterface $user) {
  // For the case when we create an order, or the owner id matches, we return
  // 'author'.
  if ($order instanceof \Drupal\user\EntityOwnerInterface && ($order->getOwner()->isAnonymous() || $order->getOwner()->id() === $user->id())) {
    return 'author';
  }
  // Otherwise, check if the user is the service provider.
  elseif ($order->hasField('field_service_provider')) {
    $service_provider = $order->get('field_service_provider')->referencedEntities();
    if (!empty($service_provider) && $service_provider[0]->id() == $user->id()) {
      return 'service_provider';
    }
  }
  // By default, we return the 'none' string.
  return 'none';
}

/**
 * Returns a map with the valid transitions for specific user roles.
 *
 * These roles are however not platform roles. For the moment, there are only 2
 * possible: 'author' and 'service_provider'. They make sense only in the
 * context of an entity.
 *
 * @param string $role
 *  The role name. Can be 'author' or 'service_provider' for the moment.
 * @param \Drupal\Core\Entity\ContentEntityInterface $entity
 *  Optiona, The entity for which we get the transitions.
 *
 * @return array
 *  The array has as key the user role, and as values an array with valid
 *  transitions.
 */
function emarket_order_get_valid_transitions_per_user_role($role, \Drupal\Core\Entity\ContentEntityInterface $entity = NULL) {
  $transitions = array(
    'author' => array(
      'draft_draft',
      'draft_submit',
      'submitted_draft',
      'submitted_submitted',
      'submitted_aborted',
      'accepted_aborted',
      'needs_clarification_draft',
      'needs_clarification_submited',
      'needs_clarification_aborted',
      'rejected_draft',
      'rejected_submitted',
      'rejected_aborted',
    ),
    'service_provider' => array(
      'submitted_accepted',
      'submitted_needs_clarification',
      'submitted_rejected',
      'accepted_accepted',
      'accepted_needs_clarification',
      'accepted_rejected',
      'accepted_progress',
      'needs_clarification_accepted',
      'needs_clarification_needs_clarification',
      'needs_clarification_rejected',
      'progress_needs_clarification',
      'progress_delivery',
      'delivery_done',
    ),
  );
  // @todo: does this code really belong here?
  // @todo: checking the anonymous user here is a bit hack-ish.
  if (\Drupal::currentUser()->isAnonymous() && !empty($entity) && $entity->hasField('field_order_confirmed')) {
    $confirmed = $entity->get('field_order_confirmed')->getValue();
    // If the order is not yet confirmed, then the only available transition
    // should be for author to be able to create a draft.
    if (empty($confirmed['value'])) {
      $transitions['author'] = array('draft_draft');
      unset($transitions['service_provider']);
    }
  }
  return !empty($role) ? $transitions[$role] : $transitions;
}
